---
title: "102-DArT"
output: html_document
date: "2025-11-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message=FALSE)
```

```{r}
library(tidyverse)
library(raster)
library(ozmaps)
library(ggrepel)
library(ggspatial)
```

```{r, eval=FALSE}
meta<-read_csv("meta/nema.metadata.edited.csv") %>% filter(include!="delete") %>% filter(tissues=="yes")
meta %>% write_csv("meta/meta-filtered.csv")
```

```{r}
meta<-read_csv("meta/meta-filtered-edited.csv")
meta$Taxon<-factor(meta$Taxon, levels=c("erebi","richardsoni","bulleri","paracome","Pilbara sp. nov.","papuensis","come","vlaminghi"))
```

```{r}
samples<-meta %>% group_by(Taxon, river, lat, long) %>% summarize(N=n())


meta %>% group_by(Taxon) %>% summarize(Count=n())
```


## Plot on Australia


```{r}
oz <- ozmap_data("states")
ggplot(oz) +
  geom_sf() +
  geom_jitter(data=samples, aes(x=long, y=lat, size=N, fill=Taxon, shape=Taxon), alpha=0.75) +
  scale_shape_manual(values=c(21,21,21,21,21,22,23,24))
```

```{r}
d3<-meta
domain <- c(min(d3$long)-8, max(d3$long)+8, min(d3$lat)-8, max(d3$lat)+8)
```


```{r, eval=FALSE}
nat.earth<-stack("~/github/fish-lake/data/earth/NE2_HR_LC_SR_W_DR/NE2_HR_LC_SR_W_DR.tif")

nat.crop <- crop(nat.earth, y=extent(domain))

rast.table <- data.frame(xyFromCell(nat.crop, 1:ncell(nat.crop)),
                         getValues(nat.crop/255))


rast.table$rgb <- with(rast.table, rgb(NE2_HR_LC_SR_W_DR_1,
                                       NE2_HR_LC_SR_W_DR_2,
                                       NE2_HR_LC_SR_W_DR_3,
                                       1))

save(rast.table, file="data/earth/rast.rda")
```

```{r}
load("data/earth/rast.rda")
```

```{r}
mdb <-sf::st_read("/Users/mac/Dropbox/Australian-fishes/data/mdb.kml")
eyre<-sf::read_sf("/Users/mac/Dropbox/Australian-fishes/data/LEB_RiverBasin_v01/LEB_RiverBasin.shp")
#ggplot() + geom_sf(data=mdb, alpha=0.0) + geom_sf(data=eyre)
ecos<-sf::read_sf("/Users/mac/Dropbox/Australian-fishes/data/GIS_hs_snapped/feow_hydrosheds.shp")
ecos<-ecos[ecos$FEOW_ID %in% c(802,803,805,806,807,808),]
```

```{r}
ggplot() +
  geom_raster(data = rast.table, mapping = aes(x = x, y = y), fill = rast.table$rgb, interpolate = TRUE)  +
  #geom_sf(data=oz, fill=NA) +
  #geom_sf(data=mdb, alpha=0.25) +
  geom_sf(data=ecos, alpha=0.15) +
  geom_jitter(data=samples, aes(x=long, y=lat, size=N, fill=Taxon, shape=Taxon), alpha=0.75) +
  scale_shape_manual(values=c(21,21,21,21,21,22,23,24)) +
  coord_sf(xlim = c(domain[1]+3,domain[2]-5), ylim=c(domain[3]+2, domain[4]-5)) +
  ylab("Latitude\n") +
  xlab("\nLongitude") +
  theme_bw() +
  theme(panel.grid=element_blank()) 

ggsave("outputs/102/nematalosa-sampling.pdf", width=7, height=5)
ggsave("outputs/102/nematalosa-sampling.jpeg", width=7, height=5)

```

